require "monroe.plugins"
require "monroe.keymap"
require "monroe.options"
require "monroe.cmp"
require "monroe.lsp"
require "monroe.treesitter"
require "monroe.autopairs"
require "monroe.gitsigns"
require "monroe.nvimtree"

